export enum PermissionModuleEnum {
  staffs = 'Authentication.Staffs',
  shops = 'Authentication.Shops',
  products = 'ProductManagement.Products',
  priceLists = 'ProductManagement.PriceLists',
  suppliers = 'CustomerManagement.Suppliers',
  customers = 'CustomerManagement.Customers',
  goodsReceivedNotes = 'InventoryManagement.GoodsReceivedNotes',
  goodsDeliveryNotes = 'InventoryManagement.GoodsDeliveryNotes',
  store = 'InventoryManagement.Store',
  orders = 'Ordering.Orders',
  receipts = 'CashBookManagement.Receipts',
  printing = 'SettingManagement.Printing',
  reports = 'RolePermission.Reports',
  invoices = 'Billing.Invoices',
}

export enum PermissionActionEnum {
  approve = 'Approve',
  cancel = 'Cancel',
  configurePrintingTemplate = 'ConfigurePrintingTemplate',
  create = 'Create',
  delete = 'Delete',
  discountBill = 'DiscountBill',
  discountProduct = 'DiscountProduct',
  edit = 'Edit',
  groupUpdate = 'GroupUpdate',
  impersonateCancel = 'ImpersonateCancel',
  impersonateCreate = 'ImpersonateCreate',
  impersonateEdit = 'ImpersonateEdit',
  inventory = 'Inventory',
  negativeStockSetting = 'NegativeStockSetting',
  overview = 'Overview',
  pay = 'Pay',
  revenue = 'Revenue',
  sales = 'Sales',
  shopUserRevenue = 'ShopUserRevenue',
  sendInvitation = 'SendInvitation',
  cancelInvitation = 'CancelInvitation',
  unlockAndLockAccount = 'UnlockAndLockAccount',
  view = 'View',
  viewAll = 'ViewAll',
  issue = 'Issue',
  editPending = 'EditPending',
  deletePending = 'DeletePending',
  issueInvoice = 'IssueInvoice',
  inventoryInOut = 'InventoryInOut',
  customerAccountsReceivable = 'CustomerAccountsReceivable',
}
